version: 2
models:
  - name: trajectory_summary
    description: This model aggregates the max speed, min speed, max acceleration, total time during the trip, and the total distance covered during the trip.
    columns:
      - name: track_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: vehicle_summary
    description: This model aggregates the max speed, min speed, fastest time, total time during the trip covered during the trip.
    columns:
      - name: track_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: full_summary
    description: This model aggregates the max speed, min speed, max acceleration, total time during the trip, and the total distance covered during the trip.
    columns:
      - name: track_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: fastest_vehicle
    description: The vehicle that had the fastest time during the trip
    columns:
      - name: track_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: total_vehicles_per_type
    description: The total number of vehicles per type and their distance covered
    columns:
      - name: total_vehicles
        description: Total number of vehicles