data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: https://cb43547.ap-south-1.aws.snowflakecomputing.com
      user: hilla
      password: Banama253#
      role: dbt_role
      database: dbt_db
      warehouse: dbt_wh
      schema: dbt_schema
      threads: 10
      client_session_keep_alive: false